cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/gritbear/Dropbox/ELEC 537/Elec537FinalProject/repos/ns-3-allinone/ns-3-dev/.waf-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/home/gritbear/Dropbox/ELEC 537/Elec537FinalProject/repos/ns-3-allinone/ns-3-dev/.waf-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 169270988: cxx test.cc -> test.cc.1.o}\n[\'/usr/bin/g++\', \'-O0\', \'-ggdb\', \'-g3\', \'-Wall\', \'-Werror\', \'-DNS3_ASSERT_ENABLE\', \'-DNS3_LOG_ENABLE\', \'-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DHAVE_PYTHON_H=1\', \'../test.cc\', \'-c\', \'-o\', \'test.cc.1.o\']\n'
